2025-03-01 09:21:30 - INFO - Starting keyword scraper for website: https://en.wikipedia.org
2025-03-01 09:21:30 - INFO - Keywords to search: ['war', 'climate', 'politics']
2025-03-01 09:21:32 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:21:37 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:21:38 - INFO - Initialized driver pool with 2 drivers
2025-03-01 09:21:40 - ERROR - Error loading page https://en.wikipedia.org: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-03-01 09:21:43 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f86540>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:43 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f87f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:43 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f86ff0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:43 - ERROR - Error loading page https://en.wikipedia.org/w/index.php?title=Special:UrlShortener&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMain_Page: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee050c380>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:21:45 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee050c7d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:45 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee050ca70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:45 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee050ccb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:45 - ERROR - Error loading page https://en.wikipedia.org/wiki/Luxor: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee050cef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:21:48 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f86e40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:48 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f86450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:48 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f87830>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:48 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:About: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f87710>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:21:50 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f85e20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:50 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f86960>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:50 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f878f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:50 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Selected_anniversaries: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f86bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:21:52 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f87830>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:52 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f87410>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:52 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f868d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:52 - ERROR - Error loading page https://en.wikipedia.org/wiki/Friedrich_Merz: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0f867b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:21:53 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee127dd30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:53 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0063170>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:53 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0063350>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:53 - ERROR - Error loading page https://en.wikipedia.org/wiki/Anactoria: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0063530>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:21:56 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee00638f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:56 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0063b30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:56 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0063d10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:56 - ERROR - Error loading page https://en.wikipedia.org/wiki/Yuika_(singer): HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee0063ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:21:58 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb5bede0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:58 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb5bec00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:58 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb5be930>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:21:58 - ERROR - Error loading page https://en.wikipedia.org/w/index.php?title=Special:QrCode&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMain_Page: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb5beff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:00 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb5bf3b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:00 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb5bf5f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:00 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb5bf7d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:00 - ERROR - Error loading page https://en.wikipedia.org/wiki/Klaus_Iohannis: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb5bf9b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:02 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb30a840>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:02 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb30aba0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:02 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb30ad80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:02 - ERROR - Error loading page https://en.wikipedia.org/wiki/Jeong_Su-il: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb30af60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:04 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb30b320>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:04 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb30b560>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:04 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb30b740>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:04 - ERROR - Error loading page https://en.wikipedia.org/wiki/Mahamoud_Ali_Youssouf: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb30b920>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:05 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb30bb60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:05 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb30bda0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:05 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb30bfe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:05 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Contents: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb340380>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:07 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edaec6fc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:07 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edaec6ff0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:07 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edaec7290>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:07 - ERROR - Error loading page https://en.wikipedia.org/wiki/Free_content: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edaec7470>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:09 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edaec7830>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:09 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edaec7a70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:09 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edaec7c50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:09 - ERROR - Error loading page https://en.wikipedia.org/w/index.php?title=Main_Page&action=info: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edb5bf0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:11 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edaec7500>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:11 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edaec70e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:11 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edaec6fc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:11 - ERROR - Error loading page https://en.wikipedia.org/wiki/February_28: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edaec7e30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:13 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edaec7f20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:13 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edad20080>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:13 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edad202c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:13 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Village_pump: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716edad204a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:16 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda510cb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:16 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda511700>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:16 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda5112e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:16 - ERROR - Error loading page https://en.wikipedia.org/wiki/Bosnian_War: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda510f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:18 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda510ec0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:18 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda511b80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:18 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda511dc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:18 - ERROR - Error loading page https://en.wikipedia.org/wiki/File:2025-02-23_Bundestagswahl_%E2%80%93_Wahlabend_CDU_by_Sandro_Halank%E2%80%93084.jpg: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda6dfdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:20 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda34ea50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:20 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda34ffe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:20 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda364710>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:20 - ERROR - Error loading page https://en.wikipedia.org/wiki/Utah_Democratic_Party: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda364740>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:21 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda364a40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:21 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda364cb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:21 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda364e90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:21 - ERROR - Error loading page https://en.wikipedia.org/wiki/Special:SpecialPages: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda365070>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:23 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda34ef00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:23 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda34f860>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:23 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda34ecf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:23 - ERROR - Error loading page https://en.wikipedia.org/wiki/Huguenots: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716eda34eba0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:26 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee041c200>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:26 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee041c230>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:26 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee041c530>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:26 - ERROR - Error loading page https://en.wikipedia.org/wiki/1869: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee041c770>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:28 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee04dd610>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:28 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee04dd820>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:28 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee04dda00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:28 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Recent_additions: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee04ddbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:30 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee04dde50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:30 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee04ddf70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:30 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee04de1e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync
2025-03-01 09:22:30 - ERROR - Error loading page https://en.wikipedia.org/wiki/March_2: HTTPConnectionPool(host='localhost', port=39829): Max retries exceeded with url: /session/9d2f95c05158e2e3be0c5346057ba856/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x716ee04de3c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:22:30 - INFO - Closed all 2 drivers in the pool
2025-03-01 09:26:50 - INFO - Starting keyword scraper for website: https://en.wikipedia.org
2025-03-01 09:26:50 - INFO - Keywords to search: ['war', 'climate', 'politics']
2025-03-01 09:26:52 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:26:55 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:26:56 - INFO - Initialized driver pool with 2 drivers
2025-03-01 09:26:57 - ERROR - Error loading page https://en.wikipedia.org: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-03-01 09:27:00 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8b82930>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:00 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8b82660>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:00 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8108620>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:00 - ERROR - Error loading page https://en.wikipedia.org/wiki/Roger_North_(biographer): HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8108710>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:02 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8108b60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:02 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8108e00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:02 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8109040>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:02 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Teahouse: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8109280>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:04 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd31ee630>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:04 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd302a690>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:04 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd3045e50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:04 - ERROR - Error loading page https://en.wikipedia.org/w/index.php?title=Special:DownloadAsPdf&page=Main_Page&action=show-download-screen: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd306e0f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:06 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8b81d30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:06 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8b81af0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:06 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8b81fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:06 - ERROR - Error loading page https://en.wikipedia.org/wiki/Butt_of_malmsey: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8b82fc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:08 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8b82ea0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:08 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8b83a10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:08 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8b824e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:08 - ERROR - Error loading page https://en.wikipedia.org/wiki/Template:POTD/2025-02-28: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8b83290>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:10 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8e1dbe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:10 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd296d4f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:10 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd296d820>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:10 - ERROR - Error loading page https://en.wikipedia.org/wiki/Timeline_of_the_Sudanese_civil_war_(2025): HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd296da00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:12 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd296ddc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:12 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd296e000>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:12 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd296e1e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:12 - ERROR - Error loading page https://en.wikipedia.org/wiki/Deke_Slayton: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd296e3c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:13 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8b82060>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:13 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8ce8c80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:13 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8ce8770>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:13 - ERROR - Error loading page https://en.wikipedia.org/wiki/Grain_Belt_Beer_Sign: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8ce8e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:15 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8ce8b90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:15 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8ce8ef0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:15 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8ce8cb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:15 - ERROR - Error loading page https://en.wikipedia.org/wiki/Whip_(politics): HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8ce85c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:17 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd21ac740>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:17 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd21af4d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:17 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd21af6b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:17 - ERROR - Error loading page https://en.wikipedia.org/wiki/User:Adam_Cuerden: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd21af8f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:19 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd81081a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:19 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd21af890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:19 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd21af740>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:19 - ERROR - Error loading page https://en.wikipedia.org/wiki/Satellite_campus: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd21ac890>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:22 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f81820>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:22 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f81a00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:22 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f81be0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:22 - ERROR - Error loading page https://en.wikipedia.org/wiki/Chairperson_of_the_African_Union_Commission: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f81dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:24 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f81580>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:24 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f81280>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:24 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1eac110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:24 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Featured_articles: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1eac350>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:26 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1eac650>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:26 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1eac950>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:26 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1eacb30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:26 - ERROR - Error loading page https://en.wikipedia.org/w/index.php?title=Special:UrlShortener&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMain_Page: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1eacf50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:28 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8ce91c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:28 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1d79be0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:28 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1d79dc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:28 - ERROR - Error loading page https://en.wikipedia.org/wiki/Free_content: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1d79fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:30 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1d7a180>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:30 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1d7a0c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:30 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1d7a5d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:30 - ERROR - Error loading page https://en.wikipedia.org/wiki/Friedrich_Merz: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1d7a7b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:32 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1a0c200>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:32 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1a0c380>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:32 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1a0c560>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:32 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:About: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1a0c740>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:35 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1a0c920>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:35 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1a0c860>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:35 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1a0cd70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:35 - ERROR - Error loading page https://en.wikipedia.org/wiki/Periodic_table: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1a0c0e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:37 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f83080>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:37 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f82390>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:37 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f82690>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:37 - ERROR - Error loading page https://en.wikipedia.org/wiki/2023_Little_Rock_tornado: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f80bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:39 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f808f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:39 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f80440>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:39 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1f80200>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:39 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Recent_additions: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd21afc80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:41 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd148ce90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:41 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd148d0a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:41 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd148cdd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:41 - ERROR - Error loading page https://en.wikipedia.org/wiki/Bundestag: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd148cef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:43 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd148c920>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:43 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd148c680>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:43 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd148cb00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:43 - ERROR - Error loading page https://en.wikipedia.org/wiki/February_28: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd148cb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:45 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd148d0a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:45 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd148cc20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:45 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd148d2b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:45 - ERROR - Error loading page https://en.wikipedia.org/wiki/Gene_Hackman: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd148d490>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:47 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd0ad0e00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:47 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd0ad1010>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:47 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd0ad1280>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:47 - ERROR - Error loading page https://en.wikipedia.org/wiki/Template_talk:Did_you_know: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd0ad14c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:49 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd0ad1370>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:49 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd0ad12e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:49 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd0ad1e20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:49 - ERROR - Error loading page https://en.wikipedia.org/wiki/President_of_Romania: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd0ad1df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:51 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd0ad1bb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:51 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd0ad1a30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:51 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd0ad2120>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:51 - ERROR - Error loading page https://en.wikipedia.org/wiki/Main_Page: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd0ad2360>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:53 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a95070>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:53 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a95160>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:53 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a953a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:53 - ERROR - Error loading page https://en.wikipedia.org/w/index.php?title=Main_Page&action=info: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a95640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:54 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a95a60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:54 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a95e80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:54 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a95fd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:54 - ERROR - Error loading page https://en.wikipedia.org/wiki/Mahamoud_Ali_Youssouf: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a96210>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:57 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd244c800>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:57 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd244c920>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:57 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd244c950>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:57 - ERROR - Error loading page https://en.wikipedia.org/wiki/Special:SpecialPages: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd244cfb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:27:59 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a94b00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:59 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2115160>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:59 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2115340>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:27:59 - ERROR - Error loading page https://en.wikipedia.org/wiki/Yap_State: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2115520>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:01 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2115880>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:01 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2115af0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:01 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2115cd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:01 - ERROR - Error loading page https://en.wikipedia.org/wiki/Abdullah_Al_Noman: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2115eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:03 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd21160f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:03 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2116330>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:03 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2116570>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:03 - ERROR - Error loading page https://en.wikipedia.org/wiki/Bosnian_War: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a94950>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:05 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2115730>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:05 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2115eb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:05 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2115ca0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:05 - ERROR - Error loading page https://en.wikipedia.org/wiki/Madge_Kendal: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd21158e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:07 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1fc26c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:07 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1fc28a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:07 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1fc2a80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:07 - ERROR - Error loading page https://en.wikipedia.org/wiki/Cal_Rampton: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1fc2c60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:10 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1fc2fc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:10 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1fc3230>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:10 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1fc3410>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:10 - ERROR - Error loading page https://en.wikipedia.org/wiki/Salt_Lake_City: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1fc35f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:12 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2767ce0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:12 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2767ec0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:12 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd27a00e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:12 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Today%27s_featured_article/March_2025: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd27a02c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:14 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd27a0620>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:14 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2767e60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:14 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2767d10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:14 - ERROR - Error loading page https://en.wikipedia.org/wiki/BAFTA_Award_for_Best_Film: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd27a0800>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:16 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a94890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:16 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a94590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:16 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a94620>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:16 - ERROR - Error loading page https://en.wikipedia.org/wiki/Illegal_dumping: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1fc2600>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:19 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd15fb4d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:19 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd15fb710>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:19 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd15fb8f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:19 - ERROR - Error loading page https://en.wikipedia.org/wiki/Nevada: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd15fbad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:21 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd220b2f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:21 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd220b4a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:21 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd220b6b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:21 - ERROR - Error loading page https://en.wikipedia.org/wiki/1936: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd220b860>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:23 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd220b080>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:23 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd220b830>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:23 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd220b4d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:23 - ERROR - Error loading page https://en.wikipedia.org/wiki/Saint_David%27s_Day: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd220b350>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:25 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd08a26c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:25 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd220b620>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:25 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd220b890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:25 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Contents: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd08a27e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:27 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd08a2b70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:27 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd08a2db0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:27 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd08a2f90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:27 - ERROR - Error loading page https://en.wikipedia.org/wiki/Colorado_River: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd08a3170>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:29 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1fc0050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:29 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd219ff50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:29 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd219fce0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:29 - ERROR - Error loading page https://en.wikipedia.org/wiki/Category:Articles_containing_French-language_text: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd219e600>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:30 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd219f6e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:30 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd1fc0140>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:30 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd219ff20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:30 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Reference_desk: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd219fb30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:32 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8d2cbf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:32 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8d2ce60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:32 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8d2d040>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:32 - ERROR - Error loading page https://en.wikipedia.org/wiki/Federation_of_Bosnia_and_Herzegovina: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8d2d220>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:34 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8d2d5e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:34 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8d2d850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:34 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8d2da90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:34 - ERROR - Error loading page https://en.wikipedia.org/wiki/Agnieszka_Mach%C3%B3wna: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8d2dcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:36 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd240f1a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:36 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd240f890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:36 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd240f6e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:36 - ERROR - Error loading page https://en.wikipedia.org/wiki/Independence_Day_(Bosnia_and_Herzegovina): HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd240f500>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:38 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd240f980>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:38 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd240fce0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:38 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd240fec0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:38 - ERROR - Error loading page https://en.wikipedia.org/wiki/Timeline_of_the_Russian_invasion_of_Ukraine_(1_January_2025_%E2%80%93_present): HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd25b00e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:39 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a61910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:39 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a61a60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:39 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a61cd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:39 - ERROR - Error loading page https://en.wikipedia.org/w/index.php?title=Main_Page&action=history: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a61d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:42 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a61be0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:42 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a61e50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:42 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a61c40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:42 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Picture_of_the_day/Archive: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a61700>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:43 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd077fcb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:43 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd077fef0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:43 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd07a8110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:43 - ERROR - Error loading page https://en.wikipedia.org/wiki/Nick_Griffin: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd07a82f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:45 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd07a8650>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:45 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd07a88c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:45 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd07a8aa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:45 - ERROR - Error loading page https://en.wikipedia.org/wiki/Jason_Kelce: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd07a8c80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:47 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd07a8410>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:47 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd07a8dd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:47 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd07a9130>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:47 - ERROR - Error loading page https://en.wikipedia.org/wiki/Klaus_Iohannis: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd07a9370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:49 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd220bc50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:49 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd03bf8f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:49 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd03bfb60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:49 - ERROR - Error loading page https://en.wikipedia.org/w/index.php?title=Special:CreateAccount&returnto=Main+Page: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd03bfe90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:51 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd022c1a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:51 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd022c170>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:51 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd022c500>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:51 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd022c740>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:53 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbc855b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:53 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbc84e90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:53 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbc85400>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:53 - ERROR - Error loading page https://en.wikipedia.org/wiki/Battle-axe_(woman): HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbc85010>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:55 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbc84bc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:55 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbc84cb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:55 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbc85010>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:55 - ERROR - Error loading page https://en.wikipedia.org/wiki/Help:Your_first_article: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbc853d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:28:58 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd220baa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:58 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbbac0e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:58 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbbac2c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:28:58 - ERROR - Error loading page https://en.wikipedia.org/wiki/Beverly_White: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbbac4a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:00 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb84cb30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:00 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb84c650>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:00 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb84c470>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:00 - ERROR - Error loading page https://en.wikipedia.org/wiki/Moira_Pollock: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb84cc20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:01 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb84c860>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:01 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb84c380>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:01 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb84c3b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:01 - ERROR - Error loading page https://en.wikipedia.org/wiki/Utah_Democratic_Party: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb84c5c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:03 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb54e3f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:03 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb54e210>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:03 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb54e060>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:03 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:File_Upload_Wizard: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb54e5a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:05 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb54e840>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:05 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb54e8d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:05 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb54ec00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:05 - ERROR - Error loading page https://en.wikipedia.org/wiki/Disability_Day_of_Mourning: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb54ee40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:08 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbb83d70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:08 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbb83cb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:08 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcac1fda0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:08 - ERROR - Error loading page https://en.wikipedia.org#bodyContent: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcac1fbc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:10 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcac841d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:10 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcac84410>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:10 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcac845f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:10 - ERROR - Error loading page https://en.wikipedia.org/wiki/Trepat: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcac847d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:13 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcac1ff80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:13 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcac1fbf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:13 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcac1faa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:13 - ERROR - Error loading page https://en.wikipedia.org/wiki/Australia_national_cricket_team: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcbb83cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:14 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcaad6330>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:14 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcaaeee40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:14 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdca912120>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:14 - ERROR - Error loading page https://en.wikipedia.org/wiki/Huguenots: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdca92a330>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:16 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9c38f80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:16 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9c39190>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:16 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9c393d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:16 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikimedia_Foundation: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9c39610>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:18 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd2a61fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:18 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9c39310>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:18 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9c39670>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:18 - ERROR - Error loading page https://en.wikipedia.org/wiki/Sarajevo_wedding_attack: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9c392e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:20 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9c399d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:20 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9c39f10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:20 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9c39e20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:20 - ERROR - Error loading page https://en.wikipedia.org/wiki/Fran%C3%A7ois,_Duke_of_Guise: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9c39af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:22 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9aa2c00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:22 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9aa2b10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:22 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9abc6b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:22 - ERROR - Error loading page https://en.wikipedia.org/wiki/Ilie_Bolojan: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9abc1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:25 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9abca70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:25 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9abcdd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:25 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9aa2960>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:25 - ERROR - Error loading page https://en.wikipedia.org/wiki/Yap_Day: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9aa2a20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:26 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9abc0e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:26 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9abc800>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:26 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9aa34d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:26 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Village_pump: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9aa2c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:28 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9aa3e90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:28 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9aa3260>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:28 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9aa3d10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:28 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Featured_pictures: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9aa2b70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:30 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9aa2570>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:30 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9aa23f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:30 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc9a84260>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:30 - ERROR - Error loading page https://en.wikipedia.org/wiki/Democratic_National_Convention: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcac1dc40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:32 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb49b500>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:32 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb49b620>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:32 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb49b800>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:32 - ERROR - Error loading page https://en.wikipedia.org/wiki/Blank_verse: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb49b9e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:35 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb3a1df0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:35 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb3a1cd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:35 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb3a2300>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:35 - ERROR - Error loading page https://en.wikipedia.org/wiki/Arizona: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb3a1c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:37 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb3a20c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:37 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb3a2630>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:37 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb3a2870>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:37 - ERROR - Error loading page https://en.wikipedia.org/wiki/Mustafa_Barzani: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdcb3a2ab0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:38 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8c2d5e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:38 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8c2d550>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:38 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8c2d820>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:38 - ERROR - Error loading page https://en.wikipedia.org/wiki/2025_African_Union_Commission_Chairperson_election: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8c2da00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:41 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8c2dd30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:41 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8c2e030>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:41 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8c2e210>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:41 - ERROR - Error loading page https://en.wikipedia.org/wiki/Thutmose_II: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8c2e3f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:43 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8965400>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:43 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8965220>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:43 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8965040>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:43 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Text_of_the_Creative_Commons_Attribution-ShareAlike_4.0_International_License: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8965820>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:45 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8826390>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:45 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8826570>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:45 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8826750>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5d943528d8928a0498e6c6cc22412115/execute/sync
2025-03-01 09:29:45 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:File_upload_wizard: HTTPConnectionPool(host='localhost', port=42547): Max retries exceeded with url: /session/5d943528d8928a0498e6c6cc22412115/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8826930>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:47 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdd8e1e6f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e4c0b4d64aead876dcca7bca4f869a8b/execute/sync
2025-03-01 09:29:47 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8826c00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e4c0b4d64aead876dcca7bca4f869a8b/execute/sync
2025-03-01 09:29:47 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc8827f80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e4c0b4d64aead876dcca7bca4f869a8b/execute/sync
2025-03-01 09:29:47 - ERROR - Error loading page https://en.wikipedia.org/wiki/Whitewash_(sport): HTTPConnectionPool(host='localhost', port=34633): Max retries exceeded with url: /session/e4c0b4d64aead876dcca7bca4f869a8b/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74bdc88275c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:29:47 - INFO - Closed all 2 drivers in the pool
2025-03-01 09:31:35 - INFO - Starting keyword scraper for website: https://en.wikipedia.org
2025-03-01 09:31:35 - INFO - Keywords to search: ['war', 'climate', 'politics']
2025-03-01 09:31:36 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:31:39 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:31:40 - INFO - Initialized driver pool with 2 drivers
2025-03-01 09:31:41 - ERROR - Error loading page https://en.wikipedia.org: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-03-01 09:31:43 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x759bee7ca8a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/701ee62ae50314e0cab504f6ca468c2b/execute/sync
2025-03-01 09:31:43 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x759bee7cbe00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/701ee62ae50314e0cab504f6ca468c2b/execute/sync
2025-03-01 09:31:43 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x759bee7ec530>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/701ee62ae50314e0cab504f6ca468c2b/execute/sync
2025-03-01 09:31:43 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:Today%27s_featured_article/March_2025: HTTPConnectionPool(host='localhost', port=54709): Max retries exceeded with url: /session/701ee62ae50314e0cab504f6ca468c2b/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x759bee7ec6e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:31:45 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x759bee7ec9b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/701ee62ae50314e0cab504f6ca468c2b/execute/sync
2025-03-01 09:31:45 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x759bee7ecbf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/701ee62ae50314e0cab504f6ca468c2b/execute/sync
2025-03-01 09:31:45 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x759bee7ece30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/701ee62ae50314e0cab504f6ca468c2b/execute/sync
2025-03-01 09:31:45 - ERROR - Error loading page https://en.wikipedia.org/wiki/Wikipedia:About_Today%27s_featured_article: HTTPConnectionPool(host='localhost', port=54709): Max retries exceeded with url: /session/701ee62ae50314e0cab504f6ca468c2b/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x759bee7ed070>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:31:47 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x759bee7ed430>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/701ee62ae50314e0cab504f6ca468c2b/execute/sync
2025-03-01 09:31:47 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x759bee7ed3a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/701ee62ae50314e0cab504f6ca468c2b/execute/sync
2025-03-01 09:31:47 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x759bee7ed760>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/701ee62ae50314e0cab504f6ca468c2b/execute/sync
2025-03-01 09:31:47 - ERROR - Error loading page https://en.wikipedia.org/wiki/Anactoria: HTTPConnectionPool(host='localhost', port=54709): Max retries exceeded with url: /session/701ee62ae50314e0cab504f6ca468c2b/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x759bee7ca840>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:31:48 - INFO - Closed all 2 drivers in the pool
2025-03-01 09:34:46 - INFO - Starting keyword scraper for website: https://en.wikipedia.org
2025-03-01 09:34:46 - INFO - Keywords to search: ['war', 'climate', 'politics']
2025-03-01 09:34:47 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:34:50 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:34:51 - INFO - Initialized driver pool with 2 drivers
2025-03-01 09:34:53 - ERROR - Error loading page https://en.wikipedia.org: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-03-01 09:34:55 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f460619e450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3dd8d4a089709c4ba7e39874151164e7/execute/sync
2025-03-01 09:34:55 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f460619fe60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3dd8d4a089709c4ba7e39874151164e7/execute/sync
2025-03-01 09:34:55 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f460619ef00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3dd8d4a089709c4ba7e39874151164e7/execute/sync
2025-03-01 09:34:55 - ERROR - Error loading page https://en.wikipedia.org/wiki/M23_campaign_(2022%E2%80%93present): HTTPConnectionPool(host='localhost', port=41033): Max retries exceeded with url: /session/3dd8d4a089709c4ba7e39874151164e7/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f46061b4290>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:34:57 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f46061b46e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3dd8d4a089709c4ba7e39874151164e7/execute/sync
2025-03-01 09:34:57 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f46061b4980>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3dd8d4a089709c4ba7e39874151164e7/execute/sync
2025-03-01 09:34:57 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f46061b4bc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3dd8d4a089709c4ba7e39874151164e7/execute/sync
2025-03-01 09:34:57 - ERROR - Error loading page https://en.wikipedia.org/wiki/Jason_Kelce: HTTPConnectionPool(host='localhost', port=41033): Max retries exceeded with url: /session/3dd8d4a089709c4ba7e39874151164e7/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f46061b4e00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:34:58 - INFO - Closed all 2 drivers in the pool
2025-03-01 09:35:24 - INFO - Starting keyword scraper for website: https://en.wikipedia.org
2025-03-01 09:35:24 - INFO - Keywords to search: ['war', 'climate', 'politics']
2025-03-01 09:35:25 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:35:28 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:35:28 - INFO - Initialized driver pool with 2 drivers
2025-03-01 09:35:30 - ERROR - Error loading page https://en.wikipedia.org: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-03-01 09:35:32 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec516e6390>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e6b06b1a560bba65359a2d2e6f237a0/execute/sync
2025-03-01 09:35:32 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec516e5d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e6b06b1a560bba65359a2d2e6f237a0/execute/sync
2025-03-01 09:35:32 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec516e7860>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e6b06b1a560bba65359a2d2e6f237a0/execute/sync
2025-03-01 09:35:32 - ERROR - Error loading page https://en.wikipedia.org/wiki/March_1: HTTPConnectionPool(host='localhost', port=44059): Max retries exceeded with url: /session/5e6b06b1a560bba65359a2d2e6f237a0/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec5170c110>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:35:34 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec5170c560>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e6b06b1a560bba65359a2d2e6f237a0/execute/sync
2025-03-01 09:35:34 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec5170c800>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e6b06b1a560bba65359a2d2e6f237a0/execute/sync
2025-03-01 09:35:34 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec5170ca40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e6b06b1a560bba65359a2d2e6f237a0/execute/sync
2025-03-01 09:35:34 - ERROR - Error loading page https://en.wikipedia.org/w/index.php?title=Special:CreateAccount&returnto=Main+Page: HTTPConnectionPool(host='localhost', port=44059): Max retries exceeded with url: /session/5e6b06b1a560bba65359a2d2e6f237a0/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec5170cc80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:35:36 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec516e5820>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e6b06b1a560bba65359a2d2e6f237a0/execute/sync
2025-03-01 09:35:36 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec516e7650>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e6b06b1a560bba65359a2d2e6f237a0/execute/sync
2025-03-01 09:35:36 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec516e69f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5e6b06b1a560bba65359a2d2e6f237a0/execute/sync
2025-03-01 09:35:36 - ERROR - Error loading page https://en.wikipedia.org/wiki/List_of_days_of_the_year: HTTPConnectionPool(host='localhost', port=44059): Max retries exceeded with url: /session/5e6b06b1a560bba65359a2d2e6f237a0/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ec516e67e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 09:35:37 - INFO - Closed all 2 drivers in the pool
2025-03-01 09:36:31 - INFO - Starting keyword scraper for website: https://www.wikipedia.com
2025-03-01 09:36:31 - INFO - Keywords to search: ['keyword1', 'keyword2']
2025-03-01 09:36:32 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:36:35 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:36:36 - INFO - Initialized driver pool with 2 drivers
2025-03-01 09:36:38 - ERROR - Error loading page https://www.wikipedia.com: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-03-01 09:36:45 - INFO - Created empty CSV file for keyword 'keyword1' at keyword_data/keyword1_wikipedia_202503010936.csv
2025-03-01 09:36:45 - INFO - Created empty CSV file for keyword 'keyword2' at keyword_data/keyword2_wikipedia_202503010936.csv
2025-03-01 09:36:45 - INFO - Closed all 2 drivers in the pool
2025-03-01 09:36:45 - INFO - Scraping complete!
2025-03-01 09:37:17 - INFO - Starting keyword scraper for website: https://www.wikipedia.com
2025-03-01 09:37:17 - INFO - Keywords to search: ['war']
2025-03-01 09:37:18 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:37:21 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:37:21 - INFO - Initialized driver pool with 2 drivers
2025-03-01 09:37:23 - ERROR - Error loading page https://www.wikipedia.com: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-03-01 09:37:26 - INFO - Created empty CSV file for keyword 'war' at keyword_data/war_wikipedia_202503010937.csv
2025-03-01 09:37:27 - INFO - Closed all 2 drivers in the pool
2025-03-01 09:37:27 - INFO - Scraping complete!
2025-03-01 09:38:50 - INFO - Starting keyword scraper for website: https://www.wikipedia.com
2025-03-01 09:38:50 - INFO - Keywords to search: ['war']
2025-03-01 09:38:51 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:38:54 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:38:56 - INFO - Initialized driver pool with 2 drivers
2025-03-01 09:38:57 - ERROR - Error loading page https://www.wikipedia.com: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-03-01 09:39:01 - INFO - Created empty CSV file for keyword 'war' at keyword_data/war_wikipedia_202503010939.csv
2025-03-01 09:39:01 - INFO - Closed all 2 drivers in the pool
2025-03-01 09:39:01 - INFO - Scraping complete!
2025-03-01 09:41:20 - INFO - Starting keyword scraper for website: https://www.wikipedia.org
2025-03-01 09:41:20 - INFO - Keywords to search: ['war']
2025-03-01 09:41:22 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:41:24 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:41:26 - INFO - Initialized driver pool with 2 drivers
2025-03-01 09:41:27 - ERROR - Error loading page https://www.wikipedia.org: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-03-01 09:41:31 - INFO - Created empty CSV file for keyword 'war' at keyword_data/war_wikipedia_202503010941.csv
2025-03-01 09:41:31 - INFO - Closed all 2 drivers in the pool
2025-03-01 09:41:31 - INFO - Scraping complete!
2025-03-01 09:42:39 - INFO - Starting keyword scraper for website: https://www.wikipedia.org
2025-03-01 09:42:39 - INFO - Keywords to search: ['war']
2025-03-01 09:42:41 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:42:43 - INFO - patching driver executable /home/trent/.local/share/undetected_chromedriver/undetected_chromedriver
2025-03-01 09:42:44 - INFO - Initialized driver pool with 2 drivers
2025-03-01 09:42:46 - ERROR - Error loading page https://www.wikipedia.org: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2025-03-01 09:42:49 - INFO - Created empty CSV file for keyword 'war' at keyword_data/war_wikipedia_202503010942.csv
2025-03-01 09:42:49 - INFO - Closed all 2 drivers in the pool
2025-03-01 09:42:49 - INFO - Scraping complete!
